### ISSUE TITLE
Unknown commit parameter 'waitFlush'

### ISSUE THREAD

**Issue by milovanderlinden** [reprovinci/solr-php-client#11]
I have been using an older, downloaded version of the solr-php-client against a SOLR-5 setup, it always worked like a charm. This weekend I decided to move to composer and came across your repo, thank you for that.

However, since this weekend, my php app is no longer able to add documents to solr with the error:

``` java
org.apache.solr.common.SolrException: Unknown commit parameter 'waitFlush'
    at org.apache.solr.handler.RequestHandlerUtils.validateCommitParams(RequestHandlerUtils.java:85)
    at org.apache.solr.handler.loader.XMLLoader.processUpdate(XMLLoader.java:267)
    at org.apache.solr.handler.loader.XMLLoader.load(XMLLoader.java:178)
    at org.apache.solr.handler.UpdateRequestHandler$1.load(UpdateRequestHandler.java:95)
    at org.apache.solr.handler.ContentStreamHandlerBase.handleRequestBody(ContentStreamHandlerBase.java:70)
    at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:156)
    at org.apache.solr.core.SolrCore.execute(SolrCore.java:2073)
    at org.apache.solr.servlet.HttpSolrCall.execute(HttpSolrCall.java:658)
    at org.apache.solr.servlet.HttpSolrCall.call(HttpSolrCall.java:457)
    at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:222)
    at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:181)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
    at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215)
    at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
...
```

I think I narrowed down the error. It is in solr-php-client\Apache\Solr\Service.php (line 919, introduction of waitflush parameter)

I would like some advice, what to do; can the waitflush parameter be removed? Or is there a better way to go?

**Comment by milovanderlinden** [comment]
Found a reference:

https://github.com/silverstripe-labs/silverstripe-fulltextsearch/issues/34

**Comment by milovanderlinden** [comment]
I think it is best to remove waitflush.

**Comment by milovanderlinden** [comment]
Solved it client side, so no issue needed here.

Old constructor:

``` php
$this->solrClient = new \Apache_Solr_Service(
  SOLR_SERVER_HOSTNAME,
  SOLR_SERVER_PORT,
  SOLR_SERVER_PATH
);
```

New constructor:

``` php
$this->solrClient = new \Apache_Solr_Service(
  SOLR_SERVER_HOSTNAME,
  SOLR_SERVER_PORT,
  SOLR_SERVER_PATH,
  false,
  new \Apache_Solr_Compatibility_Solr4CompatibilityLayer()
);
```
